//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int IdFactura { get; set; }
        public Nullable<int> IdHuesped { get; set; }
        public string DetalleCobro { get; set; }
        public decimal ValorCobro { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaEmision { get; set; }
    
        public virtual Huespedes Huespedes { get; set; }
    }
}
