//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int IdReserva { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public System.DateTime FechaEstimadaIngreso { get; set; }
        public System.DateTime FechaEstimadaSalida { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdHuesped { get; set; }
        public int IdFuncionario { get; set; }
    
        public virtual Huespedes Huespedes { get; set; }
    }
}
